-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.books
(
    id bigserial NOT NULL,
    name character(256) NOT NULL,
    register_date date NOT NULL,
    PRIMARY KEY (id),
	UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.authors
(
    id bigserial NOT NULL,
    full_name character(256) NOT NULL,
    PRIMARY KEY (id),
	UNIQUE (full_name)
);

CREATE TABLE IF NOT EXISTS public.genres
(
    id bigserial NOT NULL,
    name character(128) NOT NULL,
    PRIMARY KEY (id),
	UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.authors_for_books
(
    id bigserial NOT NULL,
    author_id bigint NOT NULL,
    book_id bigint NOT NULL,
    PRIMARY KEY (id),
	UNIQUE (author_id, book_id)
);

CREATE TABLE IF NOT EXISTS public.genres_for_books
(
    id bigserial NOT NULL,
    genre_id bigint NOT NULL,
    book_id bigint NOT NULL,
    PRIMARY KEY (id),
	UNIQUE (genre_id, book_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    firstname character(128) NOT NULL,
    lastname character(128) NOT NULL,
    middlename character(128) NOT NULL,
    phone character(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.books_for_users
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    book_id bigint NOT NULL,
    take_date date NOT NULL,
    expected_return_date date NOT NULL,
    real_return_date date,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.authors_for_books
    ADD FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.authors_for_books
    ADD FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.genres_for_books
    ADD FOREIGN KEY (genre_id)
    REFERENCES public.genres (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.genres_for_books
    ADD FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.books_for_users
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.books_for_users
    ADD FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;